In [2]:
import numpy as np


In [2]:
l = [1,2,3,4,5,6]

In [12]:
np.array(l)


array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [1,2,4,59, 'biryani',44.5,78.6, True]

In [13]:
a1=np.array(l1)

In [14]:
a2=np.array([[34,2,3],[5,6,7]])

In [11]:
a3=np.array([[[1,2,3],[45,67,21],[3,4,5]]])

In [15]:
a1

array(['1', '2', '4', '59', 'biryani', '44.5', '78.6', 'True'],
      dtype='<U11')

In [16]:
a2

array([[34,  2,  3],
       [ 5,  6,  7]])

In [17]:
a3

array([[[ 1,  2,  3],
        [45, 67, 21],
        [ 3,  4,  5]]])

In [18]:
# ndim is number of dimension 

a1.ndim

1

In [19]:
a2.ndim

2

In [20]:
a3.ndim


3

In [21]:
a1.size

8

In [22]:
a2.size

6

In [23]:
a3.size

9

In [24]:
a1.shape

(8,)

In [25]:
a2.shape

(2, 3)

In [26]:
a3.shape

(1, 3, 3)

In [29]:
np.random.randint(2,5,(3,4))

array([[2, 2, 2, 4],
       [3, 4, 3, 3],
       [2, 3, 3, 2]])

In [30]:
np.random.randint(2,5,(3,4,5))

array([[[2, 4, 3, 3, 4],
        [4, 3, 3, 3, 2],
        [4, 4, 2, 4, 3],
        [2, 3, 2, 4, 3]],

       [[4, 3, 3, 4, 2],
        [2, 2, 4, 3, 3],
        [2, 4, 2, 2, 4],
        [3, 4, 3, 3, 3]],

       [[4, 2, 4, 3, 3],
        [2, 3, 4, 2, 2],
        [2, 3, 3, 2, 4],
        [3, 2, 4, 4, 3]]])

In [31]:
np.random.rand(2,3)

array([[0.46746197, 0.60997009, 0.91825757],
       [0.9931436 , 0.73527874, 0.04714253]])

In [32]:
np.random.randn(4,4)

array([[ 1.61649874, -0.72638642, -0.57029646, -1.21401943],
       [-0.30936766, -0.53736976,  0.516574  , -1.27743327],
       [ 0.14750831,  1.08536158, -0.74632138,  0.90577477],
       [ 0.85837295,  0.06926637, -0.75524948,  1.90214211]])

In [34]:
a4=np.random.randn(4,4)

In [35]:
a4

array([[ 0.25358597,  0.53257534,  1.38119812,  1.64077554],
       [-1.23880856, -0.16578023, -1.70156662, -0.30850736],
       [-0.50776788, -0.46041707, -0.20116558,  0.1039631 ],
       [-0.04097703, -0.03249097, -1.03815144, -1.11053447]])

In [36]:
a4.reshape(2,3) # reshape supports only factorial data of previous data ex 4x4/16x1/2x8 

ValueError: cannot reshape array of size 16 into shape (2,3)

In [40]:
a4.reshape(2,8) # reshape supports only factorial data of previous data ex 4x4/16x1/2x8 

array([[ 0.25358597,  0.53257534,  1.38119812,  1.64077554, -1.23880856,
        -0.16578023, -1.70156662, -0.30850736],
       [-0.50776788, -0.46041707, -0.20116558,  0.1039631 , -0.04097703,
        -0.03249097, -1.03815144, -1.11053447]])

In [38]:
a4.reshape(8,2)

array([[ 0.25358597,  0.53257534],
       [ 1.38119812,  1.64077554],
       [-1.23880856, -0.16578023],
       [-1.70156662, -0.30850736],
       [-0.50776788, -0.46041707],
       [-0.20116558,  0.1039631 ],
       [-0.04097703, -0.03249097],
       [-1.03815144, -1.11053447]])

In [39]:
a4.reshape(1,16)

array([[ 0.25358597,  0.53257534,  1.38119812,  1.64077554, -1.23880856,
        -0.16578023, -1.70156662, -0.30850736, -0.50776788, -0.46041707,
        -0.20116558,  0.1039631 , -0.04097703, -0.03249097, -1.03815144,
        -1.11053447]])

In [41]:
a4.reshape(2,-1)

array([[ 0.25358597,  0.53257534,  1.38119812,  1.64077554, -1.23880856,
        -0.16578023, -1.70156662, -0.30850736],
       [-0.50776788, -0.46041707, -0.20116558,  0.1039631 , -0.04097703,
        -0.03249097, -1.03815144, -1.11053447]])

In [43]:
a5= np.zeros((4,4))

In [45]:
a6=np.ones((4,5))

In [46]:
a6+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [47]:
a6+ np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [48]:
a6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.array([[1,2,3,4]]).T 


array([[1],
       [2],
       [3],
       [4]])

In [55]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [56]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(2.3,3.5,1.2)

array([2.3, 3.5])

In [62]:
np.linspace(2,3, num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [63]:
np.linspace(2,3, num=50,retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [64]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [ ]:
np.eye(5)

In [4]:
import cufflinks as cf
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
!pip install cufflinks

In [6]:
cf.go_offline()

In [3]:
np.random.randn(100,3)

array([[ 1.13877248,  1.72096134,  0.21613091],
       [-0.38467324,  1.05414746, -0.28124014],
       [-1.30714885,  0.23162197, -0.58451317],
       [-0.7251924 , -0.57609426, -0.29187058],
       [-0.64392306,  1.79762542, -1.42311032],
       [-0.24346902,  0.97521009, -0.0183357 ],
       [-1.27191752,  0.57296542, -0.25621368],
       [ 1.68468952, -1.55281122,  0.01132734],
       [-0.2505365 ,  1.58112598, -0.52165861],
       [-1.01547799,  0.7602973 , -0.81969094],
       [ 2.52172036, -0.64019214, -1.55990146],
       [-0.79075022, -0.77117365,  0.39008716],
       [-0.20279097,  1.24038341, -0.30911887],
       [-0.08424201,  0.24975833,  0.04049539],
       [-0.82524693, -0.10606134, -0.45917933],
       [ 0.31341475,  1.01216252, -0.95455733],
       [ 0.3290357 ,  2.8587913 , -1.86303425],
       [-0.76619343, -1.73881172, -1.25373784],
       [ 0.45236742, -0.11283126, -1.00043095],
       [ 0.6715637 , -0.79210762,  0.39188528],
       [-2.36853584, -0.66193285,  1.088

In [9]:
df = pd.DataFrame(np.random.randn(100,3), columns=['A','B','C'])

In [10]:
df

A         B         C
0  -0.541417  0.407500 -0.649830
1   1.439522 -0.486193  0.196717
2  -0.167376 -0.331319 -1.593515
3  -0.759151 -1.577662 -1.432090
4  -0.608441 -0.066913 -0.298145
5   1.082571  1.032154  0.529568
6  -0.413839  0.041476 -0.627694
7  -0.829331 -1.279156 -0.488452
8   0.162594 -0.594043  0.417828
9   0.536387 -0.469760 -1.015705
10  0.987207 -1.000566  0.130990
11 -0.508263 -1.311565 -0.187367
12 -0.437487 -1.308954  0.169429
13 -0.317296 -0.476763 -0.383827
14 -1.336240 -1.194239  0.307834
15  0.521721 -1.309217  0.757612
16 -1.081867 -1.278046 -1.191842
17 -0.806757 -1.065423  1.586082
18  0.829921  0.987237  0.247735
19  2.275762 -0.318150  0.201429
20 -1.371254 -0.077653  1.451772
21  1.629729 -0.729864  1.411416
22 -2.166163  2.124333 -0.113455
23 -0.578855  0.749183  0.213309
24 -0.389916  0.754850 -0.647729
25 -1.114571  1.062470 -0.644698
26 -1.433021  0.183903  0.679770
27 -2.050076  0.833845 -2.224895
28  0.272515 -0.114210  0.707293
29 -1.955536  0.983407  1.462320
..       ...       ...       ...
70 -0.417286  1.415732 -0.665626
71 -0.173257 -0.719153  1.213534
72 -2.278172 -0.055816 -0.047159
73  0.225951  1.572494 -0.774334
74 -0.164048  1.109045  2.283659
75  1.059957 -0.133010 -0.302306
76  0.701478  1.073511  0.316332
77 -0.543797  0.318851  0.302890
78  0.037538  0.810683 -1.630665
79 -1.501154  1.581590 -0.996431
80  0.215036 -1.754180 -2.106771
81 -0.359146 -0.743054 -0.860805
82  1.111355  0.655245 -0.462063
83 -1.040624 -0.408958  1.718770
84 -0.015434 -0.282257  0.706048
85 -0.374616  1.346485 -1.192870
86 -0.425176  0.998758 -0.811250
87 -1.059891  0.539542  0.970713
88  0.309245 -0.300284 -1.589093
89  0.979161  0.120354 -0.466110
90  0.191139 -0.934731  0.347122
91  0.640399  0.284999 -0.215430
92  2.093033 -0.134894  1.013539
93  0.809756 -1.518572  0.250254
94 -1.495164 -0.429742 -0.236038
95 -0.640284 -1.076258 -0.761292
96  2.563602 -0.137517 -1.492732
97  1.187411  0.110504  0.354354
98 -1.178639 -1.189710  1.450237
99 -0.957227  1.242297  0.939659

[100 rows x 3 columns]

In [18]:
# find the type of data in column A

df.iplot()

In [13]:
df1=pd.DataFrame(np.random.randint(3,100,(100,1)))

In [14]:
df1

0
0    4
1   13
2   48
3   98
4   89
5   62
6   82
7   72
8   52
9   73
10  49
11  40
12  91
13  25
14  27
15  79
16   6
17  35
18  86
19  13
20  49
21  29
22  68
23   8
24  33
25  52
26  39
27  51
28  18
29  88
..  ..
70  57
71  64
72  81
73  12
74  60
75  16
76  72
77  38
78  84
79   9
80  24
81  73
82  49
83  70
84  40
85  27
86  65
87  11
88  65
89  86
90  87
91  25
92  41
93   9
94  24
95  60
96  35
97  34
98  37
99  81

[100 rows x 1 columns]

In [16]:
df1.iplot()

In [19]:
df

A         B         C
0  -0.541417  0.407500 -0.649830
1   1.439522 -0.486193  0.196717
2  -0.167376 -0.331319 -1.593515
3  -0.759151 -1.577662 -1.432090
4  -0.608441 -0.066913 -0.298145
5   1.082571  1.032154  0.529568
6  -0.413839  0.041476 -0.627694
7  -0.829331 -1.279156 -0.488452
8   0.162594 -0.594043  0.417828
9   0.536387 -0.469760 -1.015705
10  0.987207 -1.000566  0.130990
11 -0.508263 -1.311565 -0.187367
12 -0.437487 -1.308954  0.169429
13 -0.317296 -0.476763 -0.383827
14 -1.336240 -1.194239  0.307834
15  0.521721 -1.309217  0.757612
16 -1.081867 -1.278046 -1.191842
17 -0.806757 -1.065423  1.586082
18  0.829921  0.987237  0.247735
19  2.275762 -0.318150  0.201429
20 -1.371254 -0.077653  1.451772
21  1.629729 -0.729864  1.411416
22 -2.166163  2.124333 -0.113455
23 -0.578855  0.749183  0.213309
24 -0.389916  0.754850 -0.647729
25 -1.114571  1.062470 -0.644698
26 -1.433021  0.183903  0.679770
27 -2.050076  0.833845 -2.224895
28  0.272515 -0.114210  0.707293
29 -1.955536  0.983407  1.462320
..       ...       ...       ...
70 -0.417286  1.415732 -0.665626
71 -0.173257 -0.719153  1.213534
72 -2.278172 -0.055816 -0.047159
73  0.225951  1.572494 -0.774334
74 -0.164048  1.109045  2.283659
75  1.059957 -0.133010 -0.302306
76  0.701478  1.073511  0.316332
77 -0.543797  0.318851  0.302890
78  0.037538  0.810683 -1.630665
79 -1.501154  1.581590 -0.996431
80  0.215036 -1.754180 -2.106771
81 -0.359146 -0.743054 -0.860805
82  1.111355  0.655245 -0.462063
83 -1.040624 -0.408958  1.718770
84 -0.015434 -0.282257  0.706048
85 -0.374616  1.346485 -1.192870
86 -0.425176  0.998758 -0.811250
87 -1.059891  0.539542  0.970713
88  0.309245 -0.300284 -1.589093
89  0.979161  0.120354 -0.466110
90  0.191139 -0.934731  0.347122
91  0.640399  0.284999 -0.215430
92  2.093033 -0.134894  1.013539
93  0.809756 -1.518572  0.250254
94 -1.495164 -0.429742 -0.236038
95 -0.640284 -1.076258 -0.761292
96  2.563602 -0.137517 -1.492732
97  1.187411  0.110504  0.354354
98 -1.178639 -1.189710  1.450237
99 -0.957227  1.242297  0.939659

[100 rows x 3 columns]

In [22]:
df.iplot(x='A',y='B', mode = 'markers')


In [24]:
df2=sns.load_dataset('titanic')

In [25]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [26]:
# between age and fare

df2.iplot(x='age',y='fare',mode='markers')

In [27]:
df2.iplot(x='age',y='pclass',mode='markers')

In [28]:
df2.iplot(x='fare',y='pclass',mode='markers')

In [29]:
# survival male & female ratio

df2.iplot(x='sex',y='survived', kind ='bar')